# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Learn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('auth', models.CharField(max_length=20)),
                ('date', models.DateTimeField()),
                ('num_share', models.IntegerField()),
                ('num_comment', models.IntegerField()),
                ('picture', models.ImageField(upload_to='static/img/learn')),
                ('bodyPicture', models.ImageField(upload_to='static/img/learn')),
                ('article', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='blog',
            name='picture',
            field=models.ImageField(upload_to='static/img/blog'),
        ),
    ]
