# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 16:03
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0002_auto_20171016_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='article',
            field=DjangoUeditor.models.UEditorField(blank=True, verbose_name='内容'),
        ),
    ]
