# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 11:46
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0003_auto_20171017_0003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learn',
            name='bodyPicture',
        ),
        migrations.AlterField(
            model_name='blog',
            name='article',
            field=DjangoUeditor.models.UEditorField(blank=True, verbose_name='Context'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='picture',
            field=models.ImageField(upload_to='img/blogs'),
        ),
        migrations.AlterField(
            model_name='learn',
            name='article',
            field=DjangoUeditor.models.UEditorField(blank=True, verbose_name='Context'),
        ),
        migrations.AlterField(
            model_name='learn',
            name='picture',
            field=models.ImageField(upload_to='img/learns'),
        ),
    ]
