# Generated by Django 2.0.2 on 2018-02-22 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0004_auto_20180222_0800'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='名字')),
                ('email', models.EmailField(max_length=256, verbose_name='邮箱')),
                ('url', models.URLField(blank=True, verbose_name='链接')),
                ('comment', models.TextField(verbose_name='评论正文')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='BlogApp.Article')),
            ],
        ),
    ]
